#!/usr/bin/env bash

set -euo pipefail

: ${CC:=clang}
CFLAGS="-Wall -Wextra -Wpedantic -Werror -Wnull-dereference -Wformat=2
-Wshadow -Wsign-conversion -Wfloat-equal -Wswitch-enum -Wmissing-prototypes
-Wdeprecated-declarations -fsanitize=undefined -fsanitize=thread -std=c11"
LDFLAGS="-lpthread"

cc() {
	echo "CC	$@"
	$CC $CFLAGS $LDFLAGS $@
}

execute() {
	echo "EXEC	$@"
	$@
}

case "${1:-test}" in
	test)
		cc test.c -o test
		execute valgrind timeout 3s ./test
		;;

	compile_flags.txt)
		echo $CFLAGS | tr ' ' '\n' > compile_flags.txt
		;;

	*)
		echo "unknown command: '${1-}'" >&2
		exit 1
		;;
esac
